### PR TITLE
e2ee example

### PR DESCRIPTION
**Pull request by cloudwebrtc**

### CODE REVIEW

**Review by davidzhao — APPROVED** [review]
lgtm

one thing we should do before merging is to release client-sdk-swift and point this to the latest release.

**Comment by hiroshihorie** [comment]
I think we wanted to merge this one after the SDK is released so we can maintain ensure the main branch compiles with the latest SDK.

**Comment by hiroshihorie** [comment]
I'll revert this for now

**Comment by hiroshihorie** [comment]
It's back in `main` since SDK v1.1.0 was released, thanks @cloudwebrtc  !

**Pull request merged**
